version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - './_postgres/:/docker-entrypoint-initdb.d/'
      - pgdata:/var/lib/postgresql/data     


  redis: 
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

volumes:
  pgdata:
  redis_data: