// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTask) Reset() {
	*x = CreateTask{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTask) ProtoMessage() {}

func (x *CreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTask.ProtoReflect.Descriptor instead.
func (*CreateTask) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTask) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *CreateTask) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	ID            string                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	IsDone        bool                   `protobuf:"varint,4,opt,name=IsDone,proto3" json:"IsDone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Task) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Task) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Task) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *TaskList) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskID) Reset() {
	*x = TaskID{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskID) ProtoMessage() {}

func (x *TaskID) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskID.ProtoReflect.Descriptor instead.
func (*TaskID) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *TaskID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         bool                   `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *Nothing) GetDummy() bool {
	if x != nil {
		return x.Dummy
	}
	return false
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\tmessagepb\"8\n" +
	"\n" +
	"CreateTask\x12\x16\n" +
	"\x06Header\x18\x01 \x01(\tR\x06Header\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\tR\x04Body\"Z\n" +
	"\x04Task\x12\x16\n" +
	"\x06Header\x18\x01 \x01(\tR\x06Header\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\tR\x04Body\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\tR\x02ID\x12\x16\n" +
	"\x06IsDone\x18\x04 \x01(\bR\x06IsDone\"1\n" +
	"\bTaskList\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.messagepb.TaskR\x05tasks\"\x18\n" +
	"\x06TaskID\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x1f\n" +
	"\aNothing\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\bR\x05dummy2\xda\x01\n" +
	"\vTaskService\x125\n" +
	"\x06Create\x12\x15.messagepb.CreateTask\x1a\x12.messagepb.Nothing\"\x00\x120\n" +
	"\x04List\x12\x11.messagepb.TaskID\x1a\x13.messagepb.TaskList\"\x00\x121\n" +
	"\x06Delete\x12\x11.messagepb.TaskID\x1a\x12.messagepb.Nothing\"\x00\x12/\n" +
	"\x04Done\x12\x11.messagepb.TaskID\x1a\x12.messagepb.Nothing\"\x00B!Z\x1fapi-service/api/proto/messagepbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_proto_goTypes = []any{
	(*CreateTask)(nil), // 0: messagepb.CreateTask
	(*Task)(nil),       // 1: messagepb.Task
	(*TaskList)(nil),   // 2: messagepb.TaskList
	(*TaskID)(nil),     // 3: messagepb.TaskID
	(*Nothing)(nil),    // 4: messagepb.Nothing
}
var file_message_proto_depIdxs = []int32{
	1, // 0: messagepb.TaskList.tasks:type_name -> messagepb.Task
	0, // 1: messagepb.TaskService.Create:input_type -> messagepb.CreateTask
	3, // 2: messagepb.TaskService.List:input_type -> messagepb.TaskID
	3, // 3: messagepb.TaskService.Delete:input_type -> messagepb.TaskID
	3, // 4: messagepb.TaskService.Done:input_type -> messagepb.TaskID
	4, // 5: messagepb.TaskService.Create:output_type -> messagepb.Nothing
	2, // 6: messagepb.TaskService.List:output_type -> messagepb.TaskList
	4, // 7: messagepb.TaskService.Delete:output_type -> messagepb.Nothing
	4, // 8: messagepb.TaskService.Done:output_type -> messagepb.Nothing
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
